### ISSUE TITLE
Getting ready for rust 1.0

### ISSUE THREAD

**Issue by samdoshi** [samdoshi/portmidi-rs#11]
Rust 1.0 is on the way, so I'm thinking now would be a good time to do any refactoring and tidying up before the masses arrive.

I'm proposing the following changes:
 - **Remove `time.rs`**: it's not required by `midi.rs`, maybe it belongs in it's own crate? There is [rust-event](https://github.com/reem/rust-event) which might be a more full featured solution anyway.
 - **Remove `util.rs`**: again it's not required by `midi.rs`, I would have though most people would be better of with collections from the std lib rather than binding to `portmidi`'s queue library.
 - **Flatten `midi.rs` into `lib.rs`**: this also simplifies the API.
 - **Rename variables to conform to rust guidelines**
 - **0 warnings**

I'm happy to do the work, but I just want to check to see if this is the direction you'd like to go it.

**Comment by samdoshi** [comment]
Seeing as the master branch is no longer building, I've created a PR for my changes.

**Comment by musitdev** [comment]
Great. I merge the request.

**Comment by samdoshi** [comment]
Thank you, do we want to think about getting this crate on https://crates.io/? I can do it if you need me to.

Also, I've started work on a higher level midi library here: https://github.com/samdoshi/midi-rs and https://crates.io/crates/midi

**Comment by musitdev** [comment]
You're right, it's time to publidh it on crate.io. Do it, you have more experience than me.
I was thinking too on a higer level of Midi API. I have a rapide look at your work an it"s funny because (as I understand) you made a more message oriented API (message type, channel, ....) and I was thinking on a more notes oriented API (note value, pattern, sequencing ...). I think the two can be complementary. I'll try to start to write the code next week. I can create a new project and make the two API compatible or add my code to your project. Tell me what you think.

**Comment by samdoshi** [comment]
https://crates.io/crates/portmidi

Once you're more familiar with https://crates.io I can add you as a `cargo owner` so that you can manage it too, alternatively if you'd rather I could take over maintaining this crate.

My library is very much about Midi rather than music, so dealing with CC, NRPN and SysEx, but to make that easier than dealing with raw bytes. At the moment it will convert from CC, etc, to bytes (untested though), but I'd like to add code to take a byte stream and convert it to the higher level representation.

**Comment by musitdev** [comment]
Your're more actif on this crate. So It's simplier that you take the ownership on it. If you know how to do, tell me.
I'll work on a note midi API and we'll see how to adapt it to your stream.

**Comment by samdoshi** [comment]
If you're okay with it the instructions are here: https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

I'll keep it licensed under the MIT license, but add my name to the copyright statement (as well as yours).
