### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by samdoshi** [samdoshi/portmidi-rs#15]
It seems as though the documentation on rust-ci is no longer updating: http://www.rust-ci.org/musitdev/rust-portmidi I think quite a lot of people are having similar problems.

I'm using the following script to manually upload the docs to gh-pages for my midi crate: https://github.com/samdoshi/midi-rs/blob/master/other/update-gh-pages.sh

It uses https://github.com/davisp/ghp-import which is available via pypi or apt.

**Comment by musitdev** [comment]
I saw that. I thought that the rust-ci problem will be corrected. Thank for your advice. I'll see it when I'll start the midi API.
